In [13]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

data = {}
data['time_matrix'] = [
    [0, 6, 9, 8, 7, 3, 6, 2, 3, 2, 6, 6, 4, 4, 5, 9, 7],                 #0
    [6, 0, 8, 3, 2, 6, 8, 4, 8, 8, 13, 7, 5, 8, 12, 10, 14],             #1 
    [9, 8, 0, 11, 10, 6, 3, 9, 5, 8, 4, 15, 14, 13, 9, 18, 9],           #2
    [8, 3, 11, 0, 1, 7, 10, 6, 10, 10, 14, 6, 7, 9, 14, 6, 16],          #3   
    [7, 2, 10, 1, 0, 6, 9, 4, 8, 9, 13, 4, 6, 8, 12, 8, 14],             #4
    [3, 6, 6, 7, 6, 0, 2, 3, 2, 2, 7, 9, 7, 7, 6, 12, 8],                #5
    [6, 8, 3, 10, 9, 2, 0, 6, 2, 5, 4, 12, 10, 10, 6, 15, 5],            #6
    [2, 4, 9, 6, 4, 3, 6, 0, 4, 4, 8, 5, 4, 3, 7, 8, 10],                #7
    [3, 8, 5, 10, 8, 2, 2, 4, 0, 3, 4, 9, 8, 7, 3, 13, 6],               #8
    [2, 8, 8, 10, 9, 2, 5, 4, 3, 0, 4, 6, 5, 4, 3, 9, 5],                #9
    [6, 13, 4, 14, 13, 7, 4, 8, 4, 4, 0, 10, 9, 8, 4, 13, 4],            #10
    [6, 7, 15, 6, 4, 9, 12, 5, 9, 6, 10, 0, 1, 3, 7, 3, 10],             #11
    [4, 5, 14, 7, 6, 7, 10, 4, 8, 5, 9, 1, 0, 2, 6, 4, 8],               #12
    [4, 8, 13, 9, 8, 7, 10, 3, 7, 4, 8, 3, 2, 0, 4, 5, 6],               #13
    [5, 12, 9, 14, 12, 6, 6, 7, 3, 3, 4, 7, 6, 4, 0, 9, 2],              #14
    [9, 10, 18, 6, 8, 12, 15, 8, 13, 9, 13, 3, 4, 5, 9, 0, 9],           #15
    [7, 14, 9, 16, 14, 8, 5, 10, 6, 5, 4, 10, 8, 6, 2, 9, 0],            #
]
data['time_windows'] = [
    (0, 50),  # depot
    (0, 50),  # 1
    (0, 50),  # 2
    (0, 50),  # 3
    (0, 50),  # 4
    (0, 50),  # 5
    (0, 50),  # 6
    (0, 50),  # 7
    (0, 50),  # 8
    (0, 50),  # 9
    (0, 50),  # 10
    (0, 50),  # 11
    (0, 50),  # 12
    (0, 50),  # 13
    (0, 50),  # 14
    (0, 50),  # 15
    (0, 50),  # 16
]
data['pickups_deliveries'] = [
    [1, 6],
    [2, 10],
    [4, 3],
    [5, 9],
    [7, 8],
    [15, 11],
    [13, 12],
    [16, 14],
]
data['num_vehicles'] = 4
data['depot'] = 0

print(data['time_matrix'])


[[0, 6, 9, 8, 7, 3, 6, 2, 3, 2, 6, 6, 4, 4, 5, 9, 7], [6, 0, 8, 3, 2, 6, 8, 4, 8, 8, 13, 7, 5, 8, 12, 10, 14], [9, 8, 0, 11, 10, 6, 3, 9, 5, 8, 4, 15, 14, 13, 9, 18, 9], [8, 3, 11, 0, 1, 7, 10, 6, 10, 10, 14, 6, 7, 9, 14, 6, 16], [7, 2, 10, 1, 0, 6, 9, 4, 8, 9, 13, 4, 6, 8, 12, 8, 14], [3, 6, 6, 7, 6, 0, 2, 3, 2, 2, 7, 9, 7, 7, 6, 12, 8], [6, 8, 3, 10, 9, 2, 0, 6, 2, 5, 4, 12, 10, 10, 6, 15, 5], [2, 4, 9, 6, 4, 3, 6, 0, 4, 4, 8, 5, 4, 3, 7, 8, 10], [3, 8, 5, 10, 8, 2, 2, 4, 0, 3, 4, 9, 8, 7, 3, 13, 6], [2, 8, 8, 10, 9, 2, 5, 4, 3, 0, 4, 6, 5, 4, 3, 9, 5], [6, 13, 4, 14, 13, 7, 4, 8, 4, 4, 0, 10, 9, 8, 4, 13, 4], [6, 7, 15, 6, 4, 9, 12, 5, 9, 6, 10, 0, 1, 3, 7, 3, 10], [4, 5, 14, 7, 6, 7, 10, 4, 8, 5, 9, 1, 0, 2, 6, 4, 8], [4, 8, 13, 9, 8, 7, 10, 3, 7, 4, 8, 3, 2, 0, 4, 5, 6], [5, 12, 9, 14, 12, 6, 6, 7, 3, 3, 4, 7, 6, 4, 0, 9, 2], [9, 10, 18, 6, 8, 12, 15, 8, 13, 9, 13, 3, 4, 5, 9, 0, 9], [7, 14, 9, 16, 14, 8, 5, 10, 6, 5, 4, 10, 8, 6, 2, 9, 0]]


In [14]:
def tabu_search(data):
    tabu_list = [int(name) for name in range(len(data['time_matrix']))]
    solution = [[0] for c in range(data['num_vehicles'])]
    time = np.zeros(data['num_vehicles'])
    tabu_list.remove(0)
    p = np.zeros(data['num_vehicles'])
    while len(tabu_list) > 0:
        for s in range(data['num_vehicles']):    
            u = solution[s][-1]
            v = tabu_list[-1]
            distance = float("inf")
            for w in tabu_list:
                if data['time_matrix'][int(u)][int(w)] < distance:
                    distance = data['time_matrix'][int(u)][int(w)]
                    v = w
                if time[s] + data['time_matrix'][int(u)][int(w)] > data['time_windows'][v][1]:
                    break
                    return('Error time window')
                
                
            solution[s].append(v)
            ps = int(p[s])
            time[s] += data['time_matrix'][ps][v]
            print(s)
            print(int(p[s]), v)
            print(time)
            p[s] = v
            tabu_list.remove(v)
        if time[s] + data['time_matrix'][int(u)][int(v)] > data['time_windows'][v][1]:
            raise ValueError('A very specific bad thing with time windows happened.')            
    return solution, time

In [15]:
solution, time = tabu_search(data)

0
0 7
[2. 0. 0. 0.]
1
0 9
[2. 2. 0. 0.]
2
0 5
[2. 2. 3. 0.]
3
0 8
[2. 2. 3. 3.]
0
7 13
[5. 2. 3. 3.]
1
9 14
[5. 5. 3. 3.]
2
5 6
[5. 5. 5. 3.]
3
8 10
[5. 5. 5. 7.]
0
13 12
[7. 5. 5. 7.]
1
14 16
[7. 7. 5. 7.]
2
6 2
[7. 7. 8. 7.]
3
10 11
[ 7.  7.  8. 17.]
0
12 15
[11.  7.  8. 17.]
1
16 1
[11. 21.  8. 17.]
2
2 4
[11. 21. 18. 17.]
3
11 3
[11. 21. 18. 23.]


In [7]:
print(solution)
print('\n')
print(time)

[[0, 7], [0, 9], [0, 5], [0, 8]]


[2. 2. 3. 3.]


In [25]:
t = np.zeros(4)
t[2] = 5
t[2] += 7
r = t[2]
print(r)
print(t)

12.0
[ 0.  0. 12.  0.]


In [17]:
data['time_windows'][1][1]

50

In [95]:
def tabu_search(data):
    tabu_list = [int(name) for name in range(len(data['time_matrix']))]
    solution = [[0] for c in range(data['num_vehicles'])]
    time = np.zeros(data['num_vehicles'])
    tabu_list.remove(0)
    p = np.zeros(data['num_vehicles'])
    while len(tabu_list) > 0:
        for s in range(data['num_vehicles']):    
            u = solution[s][-1]
            v = tabu_list[-1]
            distance = float("inf")
            for w in tabu_list:
                if data['time_matrix'][int(u)][int(w)] < distance:
                    distance = data['time_matrix'][int(u)][int(w)]
                    v = w
            solution[s].append(v)
            ps = int(p[s])
            time[s] += data['time_matrix'][ps][v]
            print(p[s], v)
            print(time)
            p[s] = v
            tabu_list.remove(v)
            if time[s] > data['time_windows'][v][1]:
                print('Error time window')
                break
    return solution, time

In [96]:
solution, time = tabu_search(data)

0.0 7
[2. 0. 0. 0.]
0.0 9
[2. 2. 0. 0.]
0.0 5
[2. 2. 3. 0.]
0.0 8
[2. 2. 3. 3.]
7.0 13
[5. 2. 3. 3.]
9.0 14
[5. 5. 3. 3.]
5.0 6
[5. 5. 5. 3.]
8.0 10
[5. 5. 5. 7.]
13.0 12
[7. 5. 5. 7.]
14.0 16
[7. 7. 5. 7.]
6.0 2
[7. 7. 8. 7.]
10.0 11
[ 7.  7.  8. 17.]
12.0 15
[11.  7.  8. 17.]
16.0 1
[11. 21.  8. 17.]
2.0 4
[11. 21. 18. 17.]
11.0 3
[11. 21. 18. 23.]
