In [61]:
import numpy as np
from matplotlib import pyplot as plt

data = {}
data['time_matrix'] = [
    [0, 6, 9, 8, 7, 3, 6, 2, 3, 2, 6, 6, 4, 4, 5, 9, 7],                 #0
    [6, 0, 8, 3, 2, 6, 8, 4, 8, 8, 13, 7, 5, 8, 12, 10, 14],             #1 
    [9, 8, 0, 11, 10, 6, 3, 9, 5, 8, 4, 15, 14, 13, 9, 18, 9],           #2
    [8, 3, 11, 0, 1, 7, 10, 6, 10, 10, 14, 6, 7, 9, 14, 6, 16],          #3   
    [7, 2, 10, 1, 0, 6, 9, 4, 8, 9, 13, 4, 6, 8, 12, 8, 14],             #4
    [3, 6, 6, 7, 6, 0, 2, 3, 2, 2, 7, 9, 7, 7, 6, 12, 8],                #5
    [6, 8, 3, 10, 9, 2, 0, 6, 2, 5, 4, 12, 10, 10, 6, 15, 5],            #6
    [2, 4, 9, 6, 4, 3, 6, 0, 4, 4, 8, 5, 4, 3, 7, 8, 10],                #7
    [3, 8, 5, 10, 8, 2, 2, 4, 0, 3, 4, 9, 8, 7, 3, 13, 6],               #8
    [2, 8, 8, 10, 9, 2, 5, 4, 3, 0, 4, 6, 5, 4, 3, 9, 5],                #9
    [6, 13, 4, 14, 13, 7, 4, 8, 4, 4, 0, 10, 9, 8, 4, 13, 4],            #10
    [6, 7, 15, 6, 4, 9, 12, 5, 9, 6, 10, 0, 1, 3, 7, 3, 10],             #11
    [4, 5, 14, 7, 6, 7, 10, 4, 8, 5, 9, 1, 0, 2, 6, 4, 8],               #12
    [4, 8, 13, 9, 8, 7, 10, 3, 7, 4, 8, 3, 2, 0, 4, 5, 6],               #13
    [5, 12, 9, 14, 12, 6, 6, 7, 3, 3, 4, 7, 6, 4, 0, 9, 2],              #14
    [9, 10, 18, 6, 8, 12, 15, 8, 13, 9, 13, 3, 4, 5, 9, 0, 9],           #15
    [7, 14, 9, 16, 14, 8, 5, 10, 6, 5, 4, 10, 8, 6, 2, 9, 0],            #
]
data['time_windows'] = [
    (0, 50),  # depot
    (0, 50),  # 1
    (0, 50),  # 2
    (0, 50),  # 3
    (0, 50),  # 4
    (0, 50),  # 5
    (0, 50),  # 6
    (0, 50),  # 7
    (0, 50),  # 8
    (0, 50),  # 9
    (0, 50),  # 10
    (0, 50),  # 11
    (0, 50),  # 12
    (0, 50),  # 13
    (0, 50),  # 14
    (0, 50),  # 15
    (0, 50),  # 16
]
data['pickups_deliveries'] = [
    [1, 6],
    [2, 10],
    [4, 3],
    [5, 9],
    [7, 8],
    [15, 11],
    [13, 12],
    [16, 14],
]
data['num_vehicles'] = 4
data['depot'] = 0

data['pickups'] = []
for j in range(len(data['pickups_deliveries'])):
    data['pickups'].append(data['pickups_deliveries'][j][0])
print(data['pickups'])

data['deliveries'] = []
for j in range(len(data['pickups_deliveries'])):
    data['deliveries'].append(data['pickups_deliveries'][j][1])
print(data['deliveries'])

if 10 in data['deliveries']:
    print(data['deliveries'].index(10))

[1, 2, 4, 5, 7, 15, 13, 16]
[6, 10, 3, 9, 8, 11, 12, 14]
1


In [62]:
def tabu_search(data):
    tabu_list = [int(name) for name in range(len(data['time_matrix']))]
    solution = [[0] for c in range(data['num_vehicles'])]
    time = np.zeros(data['num_vehicles'])
    tabu_list.remove(0)
    p = np.zeros(data['num_vehicles'])
    while len(tabu_list) > 0:
        for s in range(data['num_vehicles']):    
            u = solution[s][-1]
            v = tabu_list[-1]
            distance = float("inf")
            for w in tabu_list:
                if data['time_matrix'][int(u)][int(w)] < distance \
                    and w in data['pickups'] or (w in data['deliveries'] \
                    and data['pickups'][data['deliveries'].index(w)] not in tabu_list \
                    and data['pickups'][data['deliveries'].index(w)] in solution[s]): 
                    
                    distance = data['time_matrix'][int(u)][int(w)]
                    v = w
                if time[s] + data['time_matrix'][int(u)][int(w)] > data['time_windows'][v][1]:
                    break
                    return('Error time window')
                
                
            solution[s].append(v)
            ps = int(p[s])
            time[s] += data['time_matrix'][ps][v]
            print('vehicule', s + 1)
            print('ftom', int(p[s]),'to', v)
            print(time)
            print('\n')
            p[s] = v
            tabu_list.remove(v)
        if time[s] + data['time_matrix'][int(u)][int(v)] > data['time_windows'][v][1]:
            raise ValueError('A very specific bad thing with time windows happened.')            
    return solution, time

In [63]:
solution, time = tabu_search(data)

vehicule 1
ftom 0 to 7
[2. 0. 0. 0.]


vehicule 2
ftom 0 to 5
[2. 3. 0. 0.]


vehicule 3
ftom 0 to 13
[2. 3. 4. 0.]


vehicule 4
ftom 0 to 1
[2. 3. 4. 6.]


vehicule 1
ftom 7 to 8
[6. 3. 4. 6.]


vehicule 2
ftom 5 to 9
[6. 5. 4. 6.]


vehicule 3
ftom 13 to 12
[6. 5. 6. 6.]


vehicule 4
ftom 1 to 6
[ 6.  5.  6. 14.]


vehicule 1
ftom 8 to 2
[11.  5.  6. 14.]


vehicule 2
ftom 9 to 16
[11. 10.  6. 14.]


vehicule 3
ftom 12 to 15
[11. 10. 10. 14.]


vehicule 4
ftom 6 to 4
[11. 10. 10. 23.]


vehicule 1
ftom 2 to 10
[15. 10. 10. 23.]


vehicule 2
ftom 16 to 14
[15. 12. 10. 23.]


vehicule 3
ftom 15 to 11
[15. 12. 13. 23.]


vehicule 4
ftom 4 to 3
[15. 12. 13. 24.]




In [64]:
print(solution)
print('\n')
print('time')
print(time)


[[0, 7, 8, 2, 10], [0, 5, 9, 16, 14], [0, 13, 12, 15, 11], [0, 1, 6, 4, 3]]


time
[15. 12. 13. 24.]
